# Inspired by https://github.com/DanielGiljam/ia-2-017-0-lodge-broker/blob/c32694d67e49950093e38f9fa5248d5c18097e12/docker-compose.yml
version: '3.9'

services:
    mongo:
        image: mongo:5.0.5
        container_name: mongo
        env_file:
            - ./.env.development
        volumes:
            - ./db:/data/db
        restart: always
        command: --logpath /dev/null
        ports:
            - '27017:27017'

    api:
        container_name: api
        build: ./
        env_file:
            - ./.env.development
        volumes:
            - ./src:/products-service/src
        restart: always
        environment:
            WAIT_HOSTS: mongo:27017
        ports:
            - '${PORT:-3000}:${PORT:-3000}'
