@url=http://localhost:3000
@token=togbortdenforsakerhetsskull

POST {{url}}/product
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "id": "string",
    "name": "string",
    "description": "string",
    "manufacturer": "string",
    "price": 1,
    "chip": "string",
    "memory": 1,
    "rating": 1,
    "imageURLs": ["string"],
    "packageDimensions": {
        "width": 1,
        "height": 1,
        "depth": 1
    },
    "packageWeight": 1
}

